### ISSUE TITLE
[ Home ] Navigation Font size and Vertical Alignment

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-swap#30]
Kindly, double check Font size as they seem to be too small for desktop view.
Correct vertical alignment of 

![image](https://user-images.githubusercontent.com/37060596/37757053-9a49ea6a-2de6-11e8-9d0d-88f4aaac5ed2.png)

**Comment by nuskujoelri** [comment]
public/css/base.nav.css - update
