### ISSUE TITLE
[ Footer ] UPPERCASE Fonts for each Page's Section + Font-size

### ISSUE THREAD

**Issue by lester-ar-ibinex-tech** [AnsellCC/ibinex-swap#32]
Fonts should be in UPPERCASE for "SERVICES, SECURITY, LEGAL..." and increased FONT SIZE for "GIVE US A CALL"

![image](https://user-images.githubusercontent.com/37060596/37757473-24224132-2de8-11e8-9ab5-d9baccab9041.png)

**Comment by nuskujoelri** [comment]
public/css/base.footer.css update.
